In [1]:
import pandas as pd 
import numpy as np
import os 
from math import sqrt

In [2]:
from stock_prediction.data_prep import Data_Prep
from stock_prediction.features_exo import exo_selection

In [3]:
# instantiate the Class 
prep_class = Data_Prep('vinci', 252)

In [4]:
# load the first dataframe ready to use if no more modification
data = prep_class.data_prep()

In [5]:
# function that allows us to delete some of the features we don't want to use for modelling 
# Log Return is to False by default

# *******************
# if period < 252 , don't use Annual_vol
#********************
prep_class.select_features(data, Return = True, Log_Return=False, High_Low=False, High_Close=True, Low_Close=True,
                        Volume_Change=True, Period_Volum=True, Annual_Vol=True,
                        Period_Vol=True, Return_Index=True, Volum_Index=True, Relative_Return=True)

,Date,Return_DG.PA,High-Close_DG.PA,Low-Close_DG.PA,Volume-Change_DG.PA,Period_Volum_DG.PA,Annual_Vol_DG.PA,Period_Vol_DG.PA,Return_stoxx_50,Period_Volum_stoxx_50,DG.PA_relatif
0,2017-05-31,0.015547,0.007076,0.015150,0.963615,0.331698,0.202937,0.202937,-0.001862,0.000000,0.017409
1,2017-06-01,-0.002187,0.009799,0.002456,-0.407210,-0.209472,0.202602,0.202602,0.003497,0.000000,-0.005684
2,2017-06-02,0.006833,0.002689,0.006314,-0.156808,-0.332583,0.202592,0.202592,0.006953,-0.186563,-0.000119
3,2017-06-05,-0.003713,0.005913,0.003224,-0.368494,-0.577419,0.201847,0.201847,0.000000,0.000000,-0.003713
4,2017-06-06,-0.013239,0.008727,0.001043,0.957079,-0.171234,0.201653,0.201653,-0.010479,-0.215993,-0.002760
...,...,...,...,...,...,...,...,...,...,...,...
1022,2021-05-31,-0.005139,0.014529,0.001941,0.069404,-0.453011,0.333450,0.333450,-0.007640,-0.538190,0.002501
1023,2021-06-01,0.011192,0.004044,0.006642,0.222716,-0.329363,0.333514,0.333514,0.007994,-0.340290,0.003199
1024,2021-06-02,-0.000958,0.005113,0.006433,-0.185038,-0.451458,0.332512,0.332512,0.004114,-0.369720,-0.005072
1025,2021-06-03,-0.004474,0.008347,0.008091,-0.026295,-0.464856,0.332046,0.332046,-0.002265,-0.384844,-0.002209
1026,2021-06-04,0.000000,0.002996,0.004623,-0.269841,-0.607491,0.329274,0.329274,0.002486,-0.371258,-0.002486

In [6]:
# function that add the exogenous features that you need to select 
# returns the dataframe ready to modelling 
# and the list of the columns to rebase it later - no VIX because no rebase for VIX - kept unchanged 
data = exo_selection(data, sp500=True, gold=True, eurusd=False, nasdaq=False, crude=False, vix=True)

In [7]:
data.head()

,Date,Return_DG.PA,High-Close_DG.PA,Low-Close_DG.PA,Volume-Change_DG.PA,Period_Volum_DG.PA,Annual_Vol_DG.PA,Period_Vol_DG.PA,Return_stoxx_50,Period_Volum_stoxx_50,DG.PA_relatif,Return_S&P500,Return_Gold,Vix_No_Rebase
0,2017-05-31,0.015547,0.007076,0.015150,0.963615,0.331698,0.202937,0.202937,-0.001862,0.000000,0.017409,-0.007514,0.007844,0.1041
1,2017-06-01,-0.002187,0.009799,0.002456,-0.407210,-0.209472,0.202602,0.202602,0.003497,0.000000,-0.005684,-0.003694,-0.003931,0.0989
2,2017-06-02,0.006833,0.002689,0.006314,-0.156808,-0.332583,0.202592,0.202592,0.006953,-0.186563,-0.000119,0.001219,0.007735,0.0975
3,2017-06-05,-0.003713,0.005913,0.003224,-0.368494,-0.577419,0.201847,0.201847,0.000000,0.000000,-0.003713,0.002787,0.001958,0.1007
4,2017-06-06,-0.013239,0.008727,0.001043,0.957079,-0.171234,0.201653,0.201653,-0.010479,-0.215993,-0.002760,-0.001566,0.011803,0.1045

In [8]:
# once you are ready to make the modelisation you may want to rebase 100 your indexes 
# to be able to compare them 
# give him the df you want to model and returns the df with no more Returns but the 100 base index

prep_class.Price_Rebase(data)

,Date,High-Close_DG.PA,Low-Close_DG.PA,Volume-Change_DG.PA,Period_Volum_DG.PA,Annual_Vol_DG.PA,Period_Vol_DG.PA,Period_Volum_stoxx_50,DG.PA_relatif,Vix_No_Rebase,Return_DG.PA_R,Return_stoxx_50_R,Return_S&P500_R,Return_Gold_R
0,2017-05-31,0.007076,0.015150,0.963615,0.331698,0.202937,0.202937,0.000000,0.017409,0.1041,100.000000,100.000000,100.000000,100.000000
1,2017-06-01,0.009799,0.002456,-0.407210,-0.209472,0.202602,0.202602,0.000000,-0.005684,0.0989,99.781294,100.349687,99.630597,99.606918
2,2017-06-02,0.002689,0.006314,-0.156808,-0.332583,0.202592,0.202592,-0.186563,-0.000119,0.0975,100.463127,101.047378,99.752063,100.377362
3,2017-06-05,0.005913,0.003224,-0.368494,-0.577419,0.201847,0.201847,0.000000,-0.003713,0.1007,100.090060,101.047378,100.030049,100.573903
4,2017-06-06,0.008727,0.001043,0.957079,-0.171234,0.201653,0.201653,-0.215993,-0.002760,0.1045,98.764958,99.988461,99.873415,101.761008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,2021-05-31,0.014529,0.001941,0.069404,-0.453011,0.333450,0.333450,-0.538190,0.002501,0.1676,135.047288,113.640669,61.082668,141.785351
1023,2021-06-01,0.004044,0.006642,0.222716,-0.329363,0.333514,0.333514,-0.340290,0.003199,0.1790,136.558796,114.549073,60.994414,141.815163
1024,2021-06-02,0.005113,0.006433,-0.185038,-0.451458,0.332512,0.332512,-0.369720,-0.005072,0.1748,136.427998,115.020295,61.216551,142.157980
1025,2021-06-03,0.008347,0.008091,-0.026295,-0.464856,0.332046,0.332046,-0.384844,-0.002209,0.1804,135.817573,114.759786,60.680494,139.452690
1026,2021-06-04,0.002996,0.004623,-0.269841,-0.607491,0.329274,0.329274,-0.371258,-0.002486,0.1642,135.817573,115.045048,60.680494,140.838877